### ISSUE TITLE
Import & Input New Sign Up members

### ISSUE THREAD

**Issue by lraw-uri** [ramhacks/ramhack-2021-2022#10]
The Sign up sheets from the Rhody Fest are scanned and they are on Shared google drive RamHacks 2021-2022.
There are more Sign up with QR codes. @bendahrooge takes care of QR Code Sign up.

- Input the First Name, Last Name
- Give them `since Fall 2021` tag to distinguish them from previous members.

**Comment by bendahrooge** [comment]
QR Code Sign Ups Imported ✅
